language: objective-c
osx_image: xcode7.3

env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
script: xctool -project Amplitude.xcodeproj -scheme AmplitudeTests build  CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
